export enum ContactStatus {
  NOT_ATTEMPTED = "NOT_ATTEMPTED",
  ATTEMPTED = "ATTEMPTED",
  CONTACTED = "CONTACTED",
  NEW_OPPORTUNITY = "NEW_OPPORTUNITY",
  ADDITIONAL_CONTRACT = "ADDITIONAL_CONTRACT",
  DISQUALIFIED = "DISQUALIFIED"
}